#define ACTION_COLOR            (0xC2A2DAAA)
#define ADMIN_ACTION_COLOR      (0xDAA2ACAA)
#define CMD_USAGE_COLOR         (0xBFC0C2FF)

#define COLOR_EMERALD           (0x2ECC71FF)
#define COLOR_GRAY              (0xB9C9BFFF)
#define COLOR_GREEN             (0x00FF00FF)
#define COLOR_LIGHTRED          (0xFF6347FF)
#define COLOR_ME                (0xC2A2DAAA)
#define COLOR_NEPHRITE          (0x27AE60FF)
#define COLOR_NORMAL_PLAYER     (0xEEEEEEFF)
#define COLOR_ORANGE            (0xFFA500FF)
#define COLOR_PINK              (0xFFAEC9FF)
#define COLOR_PURPLE            (0xC2A2DAAA)
#define COLOR_RED               (0xFF0000FF)
#define COLOR_SPRINGGREEN       (0x00FF7FFF)
#define COLOR_SUNFLOWER         (0xF1C40FFF)
#define COLOR_WHITE             (0xFFFFFFFF)
#define COLOR_YELLOW            (0xFFFF00FF)

#define EMBED_CANARY            "{FFEA03}"
#define EMBED_CELTIC_BLUE       "{1170CF}"
#define EMBED_EMERALD           "{2ECC71}"
#define EMBED_FOREST_GREEN      "{0C9E05}"
#define EMBED_GRAY              "{B9C9BF}"
#define EMBED_GREEN             "{00FF00}"
#define EMBED_HARLEQUIN         "{4CFA1B}"
#define EMBED_NEPHRITE          "{27AE60}"
#define EMBED_OFF_RED           "{FA0505}"
#define EMBED_ORANGE            "{F39C12}"
#define EMBED_PINK              "{FFAEC9}"
#define EMBED_RED               "{FF0000}"
#define EMBED_ROBIN_EGG_BLUE    "{11CFCF}"
#define EMBED_SPRINGGREEN       "{00FF7F}"
#define EMBED_SUNFLOWER         "{F1C40F}"
#define EMBED_WHITE             "{FFFFFF}"
#define EMBED_YELLOW            "{FFFF00}"

#define GENERAL_COLOR           (0xEEEEEEFF)

#define LOCAL_TALK_COLOR        (0xD0D0D0FF)
#define MEGAPHONE_COLOR         (0xFFFF00AA)
#define OOC_COLOR               (0xE0FFFFAA)
#define SPEECH_BUBBLE_COLOR     (0xEEEEEEFF)
#define WHISPER_COLOR           (0xFFFF00AA)
